server:
  port: 8082
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: airport-batch-service
  airport-batch:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/airport_batch
      username: root
      password: password
  airport:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/airport
      username: root
      password: password
logging:
  file:
    name: airport-batch.log